#!/usr/bin/env python3
"""Generate the H.264 entropy-coding tables from the text of ITU-T H.264 (03/2010), via `pdftotext -layout`.

  tools/gen-h264-tables.py <h264.txt> <crate src dir>

Writes `cavlc/tables.rs` (Tables 9-5, 9-7, 9-8, 9-9, 9-10) and `cabac/init_tables.rs` (Tables 9-12 to 9-33).
The generated files are committed; this script documents where the numbers came from. Only the spec is read.
"""
import re
import sys

spec = open(sys.argv[1], encoding="utf-8").read().split("\n")
out = sys.argv[2]


def find(prefix, start=0):
    for i in range(start, len(spec)):
        if spec[i].strip().startswith(prefix) and "..." not in spec[i]:
            return i
    raise SystemExit("not found: " + prefix)


def bits(tok):
    return tok.replace(" ", "")


# ---------------------------------------------------------------- CAVLC
def parse_coeff_token():
    # Rows: "<t1>  <total>  code0  code1  code2  code3  code4  code5" with codes broken into groups of four bits.
    start = find("Table 9-5 – coeff_token mapping")
    end = find("9.2.2", start)
    rows = {}
    for line in spec[start:end]:
        m = re.match(r"^\s*([0-3])\s+(\d{1,2})\s{2,}(.*)$", line)
        if not m:
            continue
        t1, total = int(m.group(1)), int(m.group(2))
        cols = re.split(r"\s{3,}", m.group(3).strip())
        if len(cols) != 6:
            continue
        rows[(t1, total)] = [None if c == "-" else bits(c) for c in cols]
    assert len(rows) == 62, len(rows)  # 4*17 - 6 impossible combinations (t1 > total)
    return rows


def parse_total_zeros():
    s = find("Table 9-7 – total_zeros tables for 4x4 blocks with tzVlcIndex 1 to 7")
    e = find("Table 9-8 – total_zeros tables for 4x4 blocks", s + 1)
    tz = {i: {} for i in range(1, 16)}
    for line in spec[s:e]:
        m = re.match(r"^\s*(\d{1,2})\s{2,}(.*)$", line)
        if not m:
            continue
        cols = re.split(r"\s{3,}", m.group(2).strip())
        if len(cols) != 7:
            continue
        for k, c in enumerate(cols):
            if c != "-":
                tz[k + 1][int(m.group(1))] = bits(c)
    s2 = e
    e2 = find("Table 9-9 – total_zeros tables for chroma DC", s2)
    for line in spec[s2:e2]:
        m = re.match(r"^\s*(\d{1,2})\s{2,}(.*)$", line)
        if not m:
            continue
        cols = re.split(r"\s{2,}", m.group(2).strip())
        if len(cols) != 8:
            continue
        for k, c in enumerate(cols):
            if c != "-":
                tz[k + 8][int(m.group(1))] = bits(c)
    # chroma DC 2x2 (a) and 2x4 (b)
    s3 = e2
    e3 = find("Table 9-10 – Tables for run_before", s3)
    dc = {1: {}, 2: {}, 3: {}}
    dc422 = {i: {} for i in range(1, 8)}
    part = None
    for line in spec[s3:e3]:
        if "(a) Chroma DC 2x2" in line:
            part = "a"
        elif "(b) Chroma DC 2x4" in line:
            part = "b"
        m = re.match(r"^\s*(\d)\s{2,}(.*)$", line)
        if not m:
            continue
        cols = re.split(r"\s{2,}", m.group(2).strip())
        if part == "a" and len(cols) == 3:
            for k, c in enumerate(cols):
                if c != "-":
                    dc[k + 1][int(m.group(1))] = bits(c)
        elif part == "b" and len(cols) == 7:
            for k, c in enumerate(cols):
                if c != "-":
                    dc422[k + 1][int(m.group(1))] = bits(c)
    return tz, dc, dc422


def parse_run_before():
    s = find("Table 9-10 – Tables for run_before")
    e = find("9.2.4", s)
    rb = {i: {} for i in range(1, 8)}
    for line in spec[s:e]:
        m = re.match(r"^\s*(\d{1,2})\s{2,}(.*)$", line)
        if not m:
            continue
        cols = re.split(r"\s{2,}", m.group(2).strip())
        run = int(m.group(1))
        if len(cols) == 7:
            for k, c in enumerate(cols):
                if c != "-":
                    rb[k + 1][run] = bits(c)
        elif run >= 8 and cols[-1] != "-":
            rb[7][run] = bits(cols[-1])  # rows below 7 print only dashes for the short tables, sometimes fewer
    return rb


def emit_vlc(name, table, doc):
    # table: dict value -> bitstring. Emit sorted (len, code, value).
    items = sorted(((len(b), int(b, 2), v) for v, b in table.items()))
    s = f"/// {doc}\npub const {name}: [(u8, u16, u8); {len(items)}] = [\n"
    for l, c, v in items:
        s += f"    ({l}, 0b{c:0{l}b}, {v}),\n"
    return s + "];\n"


def gen_cavlc():
    rows = parse_coeff_token()
    names = ["0 <= nC < 2", "2 <= nC < 4", "4 <= nC < 8", "8 <= nC (6-bit fixed length)", "nC == -1 (chroma DC 4:2:0)", "nC == -2 (chroma DC 4:2:2)"]
    s = "//! Generated by `tools/gen-h264-tables.py` from ITU-T H.264 (03/2010) clause 9.2. Do not edit.\n"
    s += "//!\n//! VLC tables as `(length, code, value)` triples. coeff_token values are `total_coeff * 4 + trailing_ones`.\n\n"
    for t in range(6):
        tab = {}
        for (t1, tot), cols in rows.items():
            if cols[t] is not None:
                tab[tot * 4 + t1] = cols[t]
        n = ["COEFF_TOKEN_0", "COEFF_TOKEN_1", "COEFF_TOKEN_2", "COEFF_TOKEN_3", "COEFF_TOKEN_CHROMA_DC", "COEFF_TOKEN_CHROMA_DC_422"][t]
        s += emit_vlc(n, tab, "coeff_token, " + names[t] + ".") + "\n"
    tz, dc, dc422 = parse_total_zeros()
    for i in range(1, 16):
        s += emit_vlc(f"TOTAL_ZEROS_{i}", tz[i], f"total_zeros for 4x4 blocks, tzVlcIndex {i}.") + "\n"
    for i in range(1, 4):
        s += emit_vlc(f"TOTAL_ZEROS_DC_{i}", dc[i], f"total_zeros for chroma DC 2x2 blocks, tzVlcIndex {i}.") + "\n"
    for i in range(1, 8):
        s += emit_vlc(f"TOTAL_ZEROS_DC422_{i}", dc422[i], f"total_zeros for chroma DC 2x4 blocks, tzVlcIndex {i}.") + "\n"
    rb = parse_run_before()
    for i in range(1, 8):
        s += emit_vlc(f"RUN_BEFORE_{i}", rb[i], f"run_before, zerosLeft {i if i < 7 else '> 6'}.") + "\n"
    s += gen_cbp()
    open(out + "/cavlc/tables.rs", "w").write(s)


def gen_cbp():
    # Table 9-4 (a): codeNum -> coded_block_pattern for ChromaArrayType 1 or 2.
    start = find("(a) ChromaArrayType is equal to 1 or 2", find("Table 9-4 – Assignment of codeNum", 12000))
    end = find("(b) ChromaArrayType is equal to 0 or 3", start)
    intra, inter = {}, {}
    for line in spec[start:end]:
        m = re.match(r"^\s*(\d{1,2})\s+(\d{1,2})\s+(\d{1,2})\s*$", line)
        if m:
            intra[int(m.group(1))] = int(m.group(2))
            inter[int(m.group(1))] = int(m.group(3))
    assert sorted(intra) == list(range(48)), sorted(intra)
    s = "/// `coded_block_pattern` for Intra_4x4 and Intra_8x8 macroblocks by `codeNum` (Table 9-4 a, ChromaArrayType 1 or 2).\n"
    s += "pub const CBP_INTRA: [u8; 48] = [" + ", ".join(str(intra[i]) for i in range(48)) + "];\n\n"
    s += "/// `coded_block_pattern` for Inter macroblocks by `codeNum` (Table 9-4 a, ChromaArrayType 1 or 2).\n"
    s += "pub const CBP_INTER: [u8; 48] = [" + ", ".join(str(inter[i]) for i in range(48)) + "];\n"
    return s


# ---------------------------------------------------------------- CABAC
def ints(line):
    return [int(x.replace("−", "-")) for x in re.findall(r"[−-]?\d+", line)]


def gen_cabac():
    # ctx -> [I, idc0, idc1, idc2] each (m, n)
    tab = {}

    def put(c, i_mn, idc):
        tab[c] = [i_mn] + idc

    # Tables 9-12 to 9-17 (small; transcribed from the spec text, stacked digits resolved with pdftotext -bbox).
    m = [20, 2, 3, 20, 2, 3, -28, -23, -6, -1, 7]
    n = [-15, 54, 74, -15, 54, 74, 127, 104, 53, 54, 51]
    for c in range(11):
        mn = (m[c], n[c])
        put(c, mn, [mn, mn, mn])

    def blk(first, ms, ns):
        for k in range(len(ms)):
            yield first + k, (ms[k], ns[k])

    pb = {}  # ctx -> [idc0, idc1, idc2]

    def pbset(first, rows):
        for idc, (ms, ns) in enumerate(rows):
            for c, mn in blk(first, ms, ns):
                pb.setdefault(c, [None, None, None])[idc] = mn

    pbset(11, [([23, 23, 21, 1, 0, -37, 5, -13, -11, 1, 12, -4, 17], [33, 2, 0, 9, 49, 118, 57, 78, 65, 62, 49, 73, 50]),
               ([22, 34, 16, -2, 4, -29, 2, -6, -13, 5, 9, -3, 10], [25, 0, 0, 9, 41, 118, 65, 71, 79, 52, 50, 70, 54]),
               ([29, 25, 14, -10, -3, -27, 26, -4, -24, 5, 6, -17, 14], [16, 0, 0, 51, 62, 99, 16, 85, 102, 57, 57, 73, 57])])
    pbset(24, [([18, 9, 29, 26, 16, 9, -46, -20, 1, -13, -11, 1, -6, -17, -6, 9], [64, 43, 0, 67, 90, 104, 127, 104, 67, 78, 65, 62, 86, 95, 61, 45]),
               ([26, 19, 40, 57, 41, 26, -45, -15, -4, -6, -13, 5, 6, -13, 0, 8], [34, 22, 0, 2, 36, 69, 127, 101, 76, 71, 79, 52, 69, 90, 52, 43]),
               ([20, 20, 29, 54, 37, 12, -32, -22, -2, -4, -24, 5, -6, -14, -6, 4], [40, 10, 0, 0, 42, 97, 127, 117, 74, 85, 102, 57, 93, 88, 44, 55])])
    pbset(40, [([-3, -6, -11, 6, 7, -5, 2, 0, -3, -10, 5, 4, -3, 0], [69, 81, 96, 55, 67, 86, 88, 58, 76, 94, 54, 69, 81, 88]),
               ([-2, -5, -10, 2, 2, -3, -3, 1, -3, -6, 0, -3, -7, -5], [69, 82, 96, 59, 75, 87, 100, 56, 74, 85, 59, 81, 86, 95]),
               ([-11, -15, -21, 19, 20, 4, 6, 1, -5, -13, 5, 6, -3, -1], [89, 103, 116, 57, 58, 84, 96, 63, 85, 106, 63, 75, 90, 101])])
    pbset(54, [([-7, -5, -4, -5, -7, 1], [67, 74, 74, 80, 72, 58]),
               ([-1, -1, 1, -2, -5, 0], [66, 77, 70, 86, 72, 61]),
               ([3, -4, -2, -12, -7, 1], [55, 79, 75, 97, 50, 60])])
    pbset(399, [([12, 11, 14], [40, 51, 59]), ([25, 21, 21], [32, 49, 54]), ([21, 19, 17], [33, 50, 61])])
    for c, v in pb.items():
        put(c, (0, 0), v)  # I-slice entries for these contexts are never used (mb_skip, B types, mvd, ref_idx)
    for c, mn in zip((399, 400, 401), [(31, 21), (31, 31), (25, 50)]):
        tab[c][0] = mn
    m = [0, 0, 0, 0, -9, 4, 0, -7, 13, 3]
    n = [41, 63, 63, 63, 83, 86, 97, 72, 41, 62]
    for k in range(10):
        mn = (m[k], n[k])
        put(60 + k, mn, [mn, mn, mn])

    # Tables 9-18 to 9-33: rows with 9 or 18 integers (ctxIdx, I m n, idc0 m n, idc1 m n, idc2 m n).
    s = find("Table 9-18 – Values of variables m and n for ctxIdx from 70 to 104", 13000)
    e = find("9.3.1.2     Initialisation process for the arithmetic decoding engine", s)
    for line in spec[s:e]:
        if "Table" in line or "Rec. ITU" in line:
            continue
        t = ints(line)
        if len(line.strip()) == 0:
            continue
        # a data row starts with a ctxIdx; skip header rows
        if len(t) in (9, 18) and re.match(r"^\s*\d+\s", line):
            for off in range(0, len(t), 9):
                c = t[off]
                if c == 641 and 541 not in tab:
                    c = 541  # the spec's Table 9-26 misprints ctxIdx 541 as 641
                v = t[off + 1:off + 9]
                tab[c] = [(v[0], v[1]), (v[2], v[3]), (v[4], v[5]), (v[6], v[7])]
    missing = [c for c in range(1024) if c not in tab and c != 276]
    assert not missing, missing[:20]
    tab[276] = [(0, 0)] * 4  # end_of_slice / I_PCM terminate: not adaptive
    s = "//! Generated by `tools/gen-h264-tables.py` from ITU-T H.264 (03/2010) Tables 9-12 to 9-33. Do not edit.\n"
    s += "//!\n//! `(m, n)` pairs per context index: `[ctxIdx][0]` is for I and SI slices, `[ctxIdx][1 + cabac_init_idc]` for P, SP and B.\n"
    s += "//! Entries that a slice type never uses are `(0, 0)`.\n\n"
    s += "/// Context initialisation values, 1024 contexts.\npub const CABAC_INIT: [[(i8, i8); 4]; 1024] = [\n"
    for c in range(1024):
        v = tab[c]
        s += "    [" + ", ".join(f"({a}, {b})" for a, b in v) + "],\n"
    s += "];\n"
    open(out + "/cabac/init_tables.rs", "w").write(s)


def gen_deblock():
    start = find("Table 8-16 – Derivation of offset dependent threshold variables", 12000)
    rows = {"alpha": [], "beta": [], "tc1": [], "tc2": [], "tc3": []}
    for line in spec[start:start + 90]:
        t = line.strip()
        nums = lambda rest: [int(x) for x in re.findall(r"\d+", rest)]
        if t.startswith("α′"):
            rows["alpha"] += nums(t[2:])
        elif t.startswith("β′"):
            rows["beta"] += nums(t[2:])
        else:
            m = re.match(r"^bS = ([123])\s+(.*)$", t)
            if m:
                rows["tc" + m.group(1)] += nums(m.group(2))
    for k, v in rows.items():
        assert len(v) == 52, (k, len(v))
    s = "//! Generated by `tools/gen-h264-tables.py` from ITU-T H.264 (03/2010) Tables 8-16 and 8-17. Do not edit.\n\n"
    s += "/// `alpha'` as a function of `indexA` (Table 8-16).\npub const ALPHA: [u8; 52] = " + str(rows["alpha"]) + ";\n\n"
    s += "/// `beta'` as a function of `indexB` (Table 8-16).\npub const BETA: [u8; 52] = " + str(rows["beta"]) + ";\n\n"
    s += "/// `t'C0` as a function of `indexA`, for `bS` 1, 2 and 3 (Table 8-17).\npub const TC0: [[u8; 52]; 3] = [\n"
    for k in ("tc1", "tc2", "tc3"):
        s += "    " + str(rows[k]) + ",\n"
    s += "];\n"
    open(out + "/decoder/deblock_tables.rs", "w").write(s)


def gen_cabac_engine():
    # Table 9-44: rangeTabLPS; each row prints two states side by side.
    start = find("Table 9-44 – Specification of rangeTabLPS", 16000)
    end = find("Table 9-45 – State transition table", start)
    lps = {}
    for line in spec[start:end]:
        t = [int(x) for x in re.findall(r"\d+", line)]
        if re.match(r"^\s*\d+\s", line) and len(t) == 10:
            lps[t[0]] = t[1:5]
            lps[t[5]] = t[6:10]
    assert sorted(lps) == list(range(64)), sorted(lps)
    # Table 9-45: transIdxLPS / transIdxMPS, 16 states per block of three rows.
    start = find("Table 9-45 – State transition table", end)
    end = find("9.3.3.2.2 Renormalization process", start)
    tl, tm = [], []
    for line in spec[start:end]:
        t = line.strip()
        if t.startswith("transIdxLPS"):
            tl += [int(x) for x in re.findall(r"\d+", t[len("transIdxLPS"):])]
        elif t.startswith("transIdxMPS"):
            tm += [int(x) for x in re.findall(r"\d+", t[len("transIdxMPS"):])]
    assert len(tl) == 64 and len(tm) == 64, (len(tl), len(tm))
    # Table 9-43: levelListIdx -> ctxIdxInc for significant (frame, field) and last, 8x8 blocks.
    start = find("Table 9-43 – Mapping of scanning position", 16000)
    end = find("Let numDecodAbsLevelEq1 denote", start)
    sig_f, sig_fld, last = {}, {}, {}
    for line in spec[start:end]:
        if not re.match(r"^\s*\d+\s", line) or "Rec." in line:
            continue
        t = [int(x) for x in re.findall(r"\d+", line)]
        if len(t) not in (4, 8):
            continue
        for off in range(0, len(t), 4):
            i = t[off]
            sig_f[i], sig_fld[i], last[i] = t[off + 1], t[off + 2], t[off + 3]
    assert sorted(sig_f) == list(range(63)), sorted(sig_f)
    s = "//! Generated by `tools/gen-h264-tables.py` from ITU-T H.264 (03/2010) Tables 9-43, 9-44 and 9-45. Do not edit.\n\n"
    s += "/// `rangeTabLPS[pStateIdx][qCodIRangeIdx]` (Table 9-44).\npub const RANGE_TAB_LPS: [[u8; 4]; 64] = [\n"
    for i in range(64):
        s += "    " + str(lps[i]) + ",\n"
    s += "];\n\n/// `transIdxLPS` (Table 9-45).\npub const TRANS_IDX_LPS: [u8; 64] = " + str(tl) + ";\n\n"
    s += "/// `transIdxMPS` (Table 9-45).\npub const TRANS_IDX_MPS: [u8; 64] = " + str(tm) + ";\n\n"
    s += "/// `ctxIdxInc` of `significant_coeff_flag` for 8x8 blocks, frame coded (Table 9-43), by `levelListIdx` 0 to 62.\n"
    s += "pub const SIG_COEFF_8X8_FRAME: [u8; 63] = " + str([sig_f[i] for i in range(63)]) + ";\n\n"
    s += "/// `ctxIdxInc` of `significant_coeff_flag` for 8x8 blocks, field coded (Table 9-43).\n"
    s += "pub const SIG_COEFF_8X8_FIELD: [u8; 63] = " + str([sig_fld[i] for i in range(63)]) + ";\n\n"
    s += "/// `ctxIdxInc` of `last_significant_coeff_flag` for 8x8 blocks (Table 9-43).\n"
    s += "pub const LAST_COEFF_8X8: [u8; 63] = " + str([last[i] for i in range(63)]) + ";\n"
    open(out + "/cabac/tables.rs", "w").write(s)


gen_cavlc()
gen_cabac()
gen_cabac_engine()
gen_deblock()
print("ok")
