#!/usr/bin/env python3
"""Generate crates/rvp-ui/src/icon_data.rs from Lucide SVGs (ISC licence, https://lucide.dev).

usage: tools/gen-icons.py            (downloads the icons from the lucide-static npm package via jsdelivr)
The generated file lists every icon as SVG path data on a 24x24 grid, stroke width 2, round caps and joins.
rect, circle and line elements are converted to paths here, so the runtime only parses `d` strings.
"""
import re, sys, urllib.request, pathlib

ICONS = [
    "play", "pause", "skip-back", "skip-forward", "rewind", "fast-forward", "volume-2", "volume-1", "volume-x",
    "maximize", "minimize", "folder-open", "subtitles", "audio-lines", "gauge", "x", "check", "chevron-right",
    "circle-alert", "settings-2", "loader-circle", "film",
]
BASE = "https://cdn.jsdelivr.net/npm/lucide-static/icons/{}.svg"


def num(attrs, k, default=0.0):
    m = re.search(r'\b%s="([^"]*)"' % k, attrs)
    return float(m.group(1)) if m else default


def fmt(v):
    s = ("%.4f" % v).rstrip("0").rstrip(".")
    return s if s else "0"


def to_paths(svg):
    out = []
    for m in re.finditer(r"<(path|rect|circle|line|polyline|polygon|ellipse)\b([^>]*)/?>", svg):
        tag, a = m.group(1), m.group(2)
        if tag == "path":
            out.append(re.search(r'\bd="([^"]*)"', a).group(1))
        elif tag == "line":
            out.append("M%s %sL%s %s" % tuple(fmt(num(a, k)) for k in ("x1", "y1", "x2", "y2")))
        elif tag == "circle":
            cx, cy, r = num(a, "cx"), num(a, "cy"), num(a, "r")
            out.append("M%s %sa%s %s 0 1 0 %s 0a%s %s 0 1 0 %s 0z" % (fmt(cx - r), fmt(cy), fmt(r), fmt(r), fmt(2 * r), fmt(r), fmt(r), fmt(-2 * r)))
        elif tag == "rect":
            x, y, w, h = num(a, "x"), num(a, "y"), num(a, "width"), num(a, "height")
            rx = num(a, "rx", num(a, "ry"))
            ry = num(a, "ry", rx)
            if rx == 0:
                out.append("M%s %sh%sv%sh%sz" % (fmt(x), fmt(y), fmt(w), fmt(h), fmt(-w)))
            else:
                out.append(
                    "M%s %sh%sa%s %s 0 0 1 %s %sv%sa%s %s 0 0 1 %s %sh%sa%s %s 0 0 1 %s %sv%sa%s %s 0 0 1 %s %sz"
                    % (fmt(x + rx), fmt(y), fmt(w - 2 * rx), fmt(rx), fmt(ry), fmt(rx), fmt(ry), fmt(h - 2 * ry),
                       fmt(rx), fmt(ry), fmt(-rx), fmt(ry), fmt(-(w - 2 * rx)), fmt(rx), fmt(ry), fmt(-rx), fmt(-ry),
                       fmt(-(h - 2 * ry)), fmt(rx), fmt(ry), fmt(rx), fmt(-ry))
                )
        else:
            raise SystemExit("unsupported element " + tag)
    return out


def main():
    lines = [
        "// @generated by tools/gen-icons.py from Lucide (ISC licence, https://lucide.dev). DO NOT EDIT.",
        "//! Icon path data: 24x24 grid, stroke width 2, round caps and joins.",
        "#![allow(missing_docs)]",
        "",
    ]
    for name in ICONS:
        svg = urllib.request.urlopen(BASE.format(name)).read().decode()
        paths = to_paths(svg)
        const = name.upper().replace("-", "_")
        body = ", ".join('"%s"' % p for p in paths)
        lines.append("pub const %s: &[&str] = &[%s];" % (const, body))
    dest = pathlib.Path(__file__).resolve().parent.parent / "crates/rvp-ui/src/icon_data.rs"
    dest.write_text("\n".join(lines) + "\n")
    print("wrote", dest)


main()
